import { test, expect } from '@/fixtures';
import { Language } from '@/types/header.types';

const EVENT_ID = 210;
const EVENT = {
  title: 'Updated Automation Event 2026',
  date: 'Sep 15, 2026',
  time: '7:30 PM',
  author: 'Abc123',
  category: 'ECONOMIC',
  status: 'Closed',
  accessType: 'Anyone registered',
  description:
    'This is a new detailed description generated by automated script. Validating edit functionality.',
};

test.describe('Event Details — open by ID', () => {
  test.beforeEach(async ({ authenticatedUser, eventDetailsPage }) => {
    void authenticatedUser;

    await eventDetailsPage.navigateToEventDetails(EVENT_ID);
    await eventDetailsPage.waitForDetailsPage();
    await eventDetailsPage.header.switchLanguage(Language.En);
  });

  test('TC-10 Open event details by ID', async ({ page, eventDetailsPage }) => {
    const { comments } = eventDetailsPage;

    test.info().annotations.push({
      type: 'issue',
      description:
        'Steps 1–2 skipped: event not found in Events list for logged-in user — <посилання на баг>',
    });

    await test.step('3: Verify the opened URL', async () => {
      await expect(page).toHaveURL(new RegExp(`/events/${EVENT_ID}$`));
    });

    await test.step('4: Verify the Event title', async () => {
      expect(await eventDetailsPage.getEventTitle()).toBe(EVENT.title);
    });

    await test.step('5: Verify the Event date and author', async () => {
      const dateAuthor = await eventDetailsPage.getDateAuthor();

      expect(dateAuthor).toContain(EVENT.date);
      expect(dateAuthor).toContain(EVENT.author);
    });

    await test.step('6: Verify the Event image', async () => {
      expect(await eventDetailsPage.isEventImageVisible()).toBe(true);
      await expect.poll(() => eventDetailsPage.isEventImageLoaded()).toBe(true);
    });

    await test.step('7: Verify the Event category', async () => {
      expect(await eventDetailsPage.getEventTag()).toBe(EVENT.category);
    });

    await test.step('8: Verify the Event date and time in the information block', async () => {
      const info = await eventDetailsPage.getEventInfo();

      expect(info).toContain(EVENT.date);
      expect(info).toContain(EVENT.time);
    });

    await test.step('9: Verify the Event status and access type', async () => {
      const info = await eventDetailsPage.getEventInfo();

      expect(info).toContain(EVENT.status);
      expect(info).toContain(EVENT.accessType);
    });

    await test.step('10: Verify the Event author in the information block', async () => {
      expect(await eventDetailsPage.getEventInfo()).toContain(EVENT.author);
    });

    await test.step('11: Verify the Event description', async () => {
      expect(await eventDetailsPage.getDescription()).toBe(EVENT.description);
    });

    await test.step('12: Verify the Event action controls', async () => {
      expect(await eventDetailsPage.isLikeButtonVisible()).toBe(true);
      expect(await eventDetailsPage.isLikesCountVisible()).toBe(true);

      expect(await eventDetailsPage.isShareButtonVisible('Share')).toBe(true);
      expect(await eventDetailsPage.isShareButtonVisible('Share on Twitter')).toBe(true);
      expect(await eventDetailsPage.isShareButtonVisible('Share on LinkedIn')).toBe(true);
      expect(await eventDetailsPage.isShareButtonVisible('Share on Facebook')).toBe(true);

      expect(await eventDetailsPage.isSaveEventButtonVisible()).toBe(true);
      expect(await eventDetailsPage.isJoinEventButtonVisible()).toBe(false);
      expect(await eventDetailsPage.isBackButtonVisible()).toBe(true);
    });

    await test.step('13: Verify the Comments section', async () => {
      await eventDetailsPage.scrollToComments();

      expect(await comments.isCommentsSectionVisible()).toBe(true);
      expect(await comments.isCommentInputVisible()).toBe(true);
      expect(await comments.isSubmitCommentButtonVisible()).toBe(true);
    });
  });
});
