import { test, expect } from '@/fixtures';

const EXISTING_EVENT_TITLE = 'New Automation Event 2026';
const UPDATED_TITLE = 'New Automation Event 2026!';
const UPDATED_DESCRIPTION = 'This is a new detailed description generated by automated script.';
const UPDATED_TAG = 'ECONOMIC';

test.describe('Events - Edit Event', () => {
  test.beforeEach(async ({ authenticatedUser }) => {
    void authenticatedUser;
  });

  test('TC-19 Verify successful updating of an existing event with valid data', async ({
    page,
    eventsPage,
    editEventPage,
    eventDetailsPage,
  }) => {
    await test.step('Open the Events page', async () => {
      await eventsPage.navigateToEventsPage();
      await eventsPage.waitForEventsPage();
    });

    await test.step("Click the 'Edit event' button for the updated event", async () => {
      const eventCard = eventsPage.getGridEventCardByTitle(EXISTING_EVENT_TITLE);

      await eventCard.clickEditEvent();
    });

    await test.step('Clear the Title field and enter the updated title', async () => {
      await editEventPage.enterTitle(UPDATED_TITLE);

      await expect(editEventPage.titleInput).toHaveValue(UPDATED_TITLE);
    });

    await test.step('Clear the Events Description and enter the updated description', async () => {
      await editEventPage.enterDescription(UPDATED_DESCRIPTION);

      await expect(editEventPage.descriptionEditor).toHaveText(UPDATED_DESCRIPTION);
    });

    await test.step('Select Economic and deselect Social initiative type', async () => {
      await editEventPage.toggleEconomicTag();
      await editEventPage.toggleSocialTag();
    });

    await test.step('Select current date plus one day', async () => {
      const tomorrow = new Date();
      tomorrow.setDate(tomorrow.getDate() + 1);

      const updatedDate = tomorrow.toLocaleDateString('en-US');

      await editEventPage.setEventDate(updatedDate);

      await expect(editEventPage.dateInput).toHaveValue(updatedDate);
    });

    await test.step("Click the 'Save event' button", async () => {
      await editEventPage.clickSaveEvent();
    });

    await test.step('Verify redirection to the Events page', async () => {
      await expect(page).toHaveURL(/#\/greenCity\/events$/);
    });

    await test.step('Verify the success notification is displayed', async () => {
      await expect(editEventPage.toastMessage).toHaveText('You have successfully updated an event');
    });

    await test.step('Verify the updated event card', async () => {
      const updatedEventCard = eventsPage.getGridEventCardByTitle(UPDATED_TITLE);

      expect(await updatedEventCard.getTitle()).toBe(UPDATED_TITLE);

      expect((await updatedEventCard.getType()).trim().toUpperCase()).toBe(UPDATED_TAG);
    });

    await test.step("Click the 'More' button", async () => {
      const updatedEventCard = eventsPage.getGridEventCardByTitle(UPDATED_TITLE);

      await updatedEventCard.clickMore();
    });

    await test.step('Verify the updated event details', async () => {
      await eventDetailsPage.waitForDetailsPage();

      expect(await eventDetailsPage.getEventTitle()).toBe(UPDATED_TITLE);

      expect(await eventDetailsPage.getDescription()).toBe(UPDATED_DESCRIPTION);

      expect((await eventDetailsPage.getEventTag()).toUpperCase()).toBe(UPDATED_TAG);
    });
  });
});
